name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      build_matrix: |
        include:
          - board: bluemicro840_v1
            shield: corne_left
          - board: bluemicro840_v1
            shield: corne_right
